mypjt/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles_url'

urlpatterns = [
    path('', views.index, name='index'), 
    path('create/', views.create, name='create'), 
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'), 
    path('<int:pk>/delete/', views.delete, name='delete'), 
]

mypjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # /articles/ 로 시작하는 요청은 articles app 가서 보세요~~
    path('articles/', include('articles.urls'))
]

mypjt/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

    # 작성 시간, 수정 시간이 DB 에 자동으로 들어가도록 설정.
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

mypjt/articles/forms.py
# app 에서 사용할 form 을 모은 모듈.

# form 의 역할: 1. form 을 쉽게 그릴 수 있게 도와줌. 2. 유효성 검사를 할 수 있게 해 줌.
# 우리가 사용자로부터 받아야 하는 데이터는 model 이다. 즉, model 과 똑같이 생긴(data 형식이 똑같은) form 이 있으면 된다.
# form 을 만들건데, model 을 참조해서 만들어야 되겠다 => ModelForm.

from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    # Meta class 에 Article model 정의.
    class Meta:
        model = Article  # Meta 야, 내가 쓰는 model 은 Article 이야....
        fields = '__all__'  # Form 에서 사용자에게 입력받을 필드를 정의. 
        # fields = ['title', 'content']  # 원래 이렇게 해 주는 게 안전하고 좋은데, 일단은 다 받기.

mypjt/articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm
from .models import Article

# 요청 처리에 필요한 함수 정의




# 게시글 목록
def index(request):
    articles = Article.objects.all().order_by('-pk')  # pk 가 큰 글(= 최신 글) 을 위로 올려준다.
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)




# 게시글 작성 화면 및 DB 저장
def create(request):
    if request.method == 'POST':  # POST 요청이라면
        # 1. 사용자가 작성한 내용을 DB에 저장 == POST
        # ModelForm 이므로 사용자가 입력한 데이터의 유효성 검사를 수행하고,
        # model instance 의 역할을 해 주면 됨.
        form = ArticleForm(data = request.POST)  # 사용자가 입력한 데이터는 request.POST 에 있으므로 그 데이터를 인자로 넘겨줌.
        if form.is_valid():  # 유효하다면
            form.save()  # 저장.
            return redirect('articles_url:index')  # 이후 목록으로 redirect
    
    else:
        # 2. 게시글 작성 화면 응답 == GET
        # ModelForm 인스턴스 만들어서 템플릿으로 전달
        form = ArticleForm()  # 비어있는 form

    context = {
        'form': form
    }
    return render(request, 'articles/create.html', context)




# 게시글 상세 화면
def detail(request, pk):
    # 상세 페이지를 보여줄 때는 게시글의 내용이 필요하다. 그러므로, pk 를 통해 DB 에서 조사한다.
    article = Article.objects.get(pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)




# 게시글 수정 화면 및 DB 저장
def update(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
    # 1. 사용자가 수정한 내용을 DB에 저장 == POST
        form = ArticleForm(data=request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles_url:detail', article.pk)

    else:
        # 2. 게시글 수정 화면 응답 == GET
        form = ArticleForm(instance=article)  # instance=article 이거 때문에 create 와 달라진다!
    
    context = {
        'form': form, 
        'article': article, 
    }
    return render(request, 'articles/update.html', context)




# 게시글 삭제 및 DB 삭제
def delete(request, pk):
    if request.method == 'POST':
        article = Article.objects.get(pk=pk)
        article.delete()
        return redirect('articles_url:index')
    return redirect('articles_url:detail', pk)

mypjt/articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
<h1>CREATE PAGE</h1>
<hr>
{% comment %}
form 요소 작성
  1. 서버에 저장해야 하니까 method 는 POST 로 작성
  2. POST 요청 보낼 때 csrf-token 이 반드시 있어야 하니까, 작성.
{% endcomment %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="작성">
</form>
{% endblock content %}

mypjt/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}
<h1>DETAIL PAGE</h1>
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
<hr>
<p>작성일: {{ article.created_at }}</p>
<p>수정일: {{ article.updated_at }}</p>
<hr>
<a href="{% url "articles_url:update" article.pk %}">[수정]</a>
<form action="{% url "articles_url:delete" article.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="삭제하기">
</form>
{% endblock content %}

mypjt/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}

<h1>INDEX PAGE</h1>
{% for each in articles %}
<a href="{% url "articles_url:detail" each.pk %}"><p>{{ each.title }}</p></a>
<hr>
{% endfor %}

{% endblock content %}

mypjt/articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}
<h1>UPDATE PAGE</h1>
<form action="{% url "articles_url:update" article.pk %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="수정">
</form>
{% endblock content %}

mypjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <a href="{% url "articles_url:index" %}">[홈으로]</a> | <a href="{% url "articles_url:create" %}">[새 글]</a>
  {% block content %}
  {% endblock content %}
</body>
</html>